version: '3.1'
services:
  xransom:
    image: xran
    restart: always
    network_mode: "host"
    stdin_open: true
    tty: true
    volumes:
      - ./:/home/xransom
    working_dir: /home/xransom
